# Generated by Django 4.1.3 on 2022-11-29 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('published_date', models.DateField()),
                ('last_updated_on', models.DateField()),
                ('approval_status', models.BooleanField(default=False)),
            ],
        ),
    ]
