# Generated by Django 4.1.3 on 2022-12-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mob_number',
            field=models.BigIntegerField(null=True),
        ),
    ]
