# Generated by Django 4.1.3 on 2022-12-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_blog_user_alter_customuser_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="last_updated_on",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="blog",
            name="published_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
